modLoader="javafml"
loaderVersion="[4.0,)"
license="MIT"

[[mods]]
modId="powergrid_batteries"
version="1.0.0"
displayName="Create: Power Grid Batteries"
authors="alebu"
description='''
An unofficial Add-on for Create: Power Grid introducing 4 tiered batteries (Small Battery, Medium Battery, High-Voltage Battery, and Power Grid Substation) with full Engineer's Goggles HUD support, Ponder scenes, and Display Links integration.
'''

[[dependencies.powergrid_batteries]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.powergrid_batteries]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.powergrid_batteries]]
modId="create"
type="required"
versionRange="[6.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.powergrid_batteries]]
modId="powergrid"
type="required"
versionRange="[0.5.0,)"
ordering="NONE"
side="BOTH"
